version: '3.8'

services:
  db:
    image: postgres:14
    container_name: coin-converter-api-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=coin_db
